# Generated by Django 6.0.2 on 2026-03-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_customer_alter_payment_options_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
    ]
