# Generated by Django 6.0.3 on 2026-03-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('cash', 'Cash')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
